### PR TITLE
Update to support more recent Lita versions

### PR DESCRIPTION
**Pull request by brodock**
Will fix help message:

```
translation missing: en-US.UTF-8.lita.handlers.high_five.help.high_five_value
```

### CODE REVIEW

**Comment by jimmycuadra** [comment]
Hmm... I don't think any of these changes are necessary to avoid that warning message. I'm not sure how you're getting a warning since the current code does load the locale file... There's also no need to increase the version dependency on lita or add pry-byebug or rack-test for this.

**Comment by brodock** [comment]
the important changes are in:

lib/lita-high-five.rb
and 
lib/lita/handlers/high_five.rb

after them, the error goes away
the other changes was more to follow 4.x template

**Comment by jimmycuadra** [comment]
I'll bet it's a load ordering issue. These changes are fine I guess, but could you change the new version to 1.0.0? It's stable at this point.

**Comment by brodock** [comment]
done

**Comment by jimmycuadra** [comment]
Gracias!

**Comment by jimmycuadra** [comment]
1.0.0 gem released.

**Pull request merged**
